version: '3.9'

services:
  mongodb:
    image: mongo:5.0
    expose:
        - 27017
    ports:
        - '27017:27017'
    volumes:
          - ./data/mongodb:/data/db
          - ./db/mongodb:/docker-entrypoint-initdb.d/
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
